=== CaetanoR/book-api/src/main/api/schemas/book-schema-output.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "author": {
      "description": "Name of the author of the book",
      "type": "string"
    },
    "id": {
      "description": "A unique number that identifies the book",
      "type": "integer"
    },
    "pages": {
      "description": "The number of pages of the book",
      "type": "integer"
    },
    "title": {
      "description": "The book's title",
      "type": "string"
    }
  },
  "required": [
    "author",
    "id",
    "pages",
    "title"
  ],
  "name": "book",
  "type": "object"
}

=== CaetanoR/book-api/src/main/api/examples/books-get-response-example.json
[
  {
    "title": "A Game of Thrones",
    "author": "George R. R. Martin",
    "pages": 694,
    "id": 1
  },
  {
    "title": "A Clash of Kings",
    "author": "George R. R. Martin",
    "pages": 768,
    "id": 2
  },
  {
    "title": "A Storm of Swords",
    "author": "George R. R. Martin",
    "pages": 973,
    "id": 3
  },
  {
    "title": "A Feast for Crows",
    "author": "George R. R. Martin",
    "pages": 976,
    "id": 4
  },
  {
    "title": "A Dance with Dragons",
    "author": "George R. R. Martin",
    "pages": 1040,
    "id": 5
  },
  {
    "title": "The Silmarillion",
    "author": "J.R.R Tolkien",
    "pages": 365,
    "id": 6
  }
]
